import Gio from 'gi://Gio';
import GLib from 'gi://GLib';
import St from 'gi://St';
import * as Main from 'resource:///org/gnome/shell/ui/main.js';

const MATUGEN_COLORS = `${GLib.get_home_dir()}/.config/matugen/matugen-colors.css`;

function hexToRgba(hex, alpha) {
    const h = String(hex).replace('#', '');
    if (h.length !== 6)
        return null;
    const r = parseInt(h.slice(0, 2), 16);
    const g = parseInt(h.slice(2, 4), 16);
    const b = parseInt(h.slice(4, 6), 16);
    return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

function parseMatugenColors(text) {
    const vars = {};
    const re = /--([a-z0-9_]+)\s*:\s*(#[0-9a-fA-F]{6})/g;
    let m;
    while ((m = re.exec(text)) !== null)
        vars[m[1]] = m[2];
    return vars;
}

function generateStylesheet(vars) {
    const c = name => vars[name] ?? '#1b2122';
    const surface = c('surface_container');
    const surfaceHigh = c('surface_container_high') ?? surface;
    const onSurface = c('on_surface');
    const onSurfaceVar = c('on_surface_variant') ?? c('on_surface');
    const primary = c('primary');
    const error = c('error');
    const scrim = c('scrim');

    const border = hexToRgba(surfaceHigh, 0.6);

    return `/* Generated by material-dock from matugen */
.material-dock-card {
    background-color: ${hexToRgba(surface, 0.82)};
    border: 1px solid ${border};
}

.dash-item-container {
    padding-right: 0px;
    padding-left: 0px;
}

#material-dock .dash-background {
    background-color: transparent;
}

.material-dock-indicator {
    margin-bottom: 2px;
}

.material-dock-indicator-dot {
    background-color: ${hexToRgba(onSurfaceVar, 0.35)};
}

.material-dock-indicator-dot.running {
    background-color: ${hexToRgba(onSurfaceVar, 0.85)};
}

.material-dock-indicator-dot.active-bar,
.material-dock-indicator-dot.focused {
    background-color: ${primary};
    border: 1px solid ${hexToRgba(scrim, 0.35)};
}

.material-dock-indicator-dot.urgent {
    background-color: ${error};
}

.material-dock-indicator-bar {
    background-color: ${hexToRgba(onSurfaceVar, 0.35)};
}

.material-dock-indicator-bar.active,
.material-dock-indicator-bar.focused {
    background-color: ${primary};
}

.material-dock-indicator-bar.running {
    background-color: ${hexToRgba(onSurfaceVar, 0.85)};
}

.material-dock-indicator-bar.urgent {
    background-color: ${error};
}

.material-dock-indicator-count {
    color: ${onSurface};
    background-color: ${hexToRgba(scrim, 0.55)};
}

.material-dock-tile:hover {
    background-color: ${hexToRgba(onSurface, 0.12)};
}

.material-dock-tile:active {
    background-color: ${hexToRgba(onSurface, 0.2)};
}

.material-dock-tile-label {
    color: ${hexToRgba(onSurface, 0.85)};
}

.material-dock-min-tile {
    background-color: ${hexToRgba(onSurface, 0.07)};
}

.material-dock-min-tile:hover {
    background-color: ${hexToRgba(onSurface, 0.15)};
}

.material-dock-min-tile-label {
    color: ${hexToRgba(onSurface, 0.9)};
}

.material-dock-min-tile-close:hover {
    background-color: ${hexToRgba(error, 0.5)};
}

.material-dock-preview-panel {
    background-color: ${hexToRgba(surfaceHigh, 0.95)};
    border: 1px solid ${border};
}

.material-dock-preview-button:hover {
    background-color: ${hexToRgba(onSurface, 0.12)};
}

.material-dock-preview-button:active {
    background-color: ${hexToRgba(onSurface, 0.2)};
}

.material-dock-preview-title {
    color: ${hexToRgba(onSurface, 0.9)};
}

.material-dock-preview-empty {
    color: ${hexToRgba(onSurface, 0.6)};
}

.material-dock-preview-more {
    color: ${hexToRgba(onSurface, 0.6)};
}

.material-dock-file-sub {
    color: ${hexToRgba(onSurface, 0.6)};
}
`;
}

export class MatugenTheme {
    constructor() {
        this._file = Gio.File.new_for_path(MATUGEN_COLORS);
        this._monitorId = 0;
        this._cssPath = `${GLib.get_tmp_dir()}/material-dock-matugen.css`;
        this._sourceId = 0;
    }

    apply() {
        if (this._load()) {
            this._startMonitor();
        }
    }

    _load() {
        try {
            const [, contents] = this._file.load_contents(null);
            const text = new TextDecoder().decode(contents);
            const vars = parseMatugenColors(text);
            if (Object.keys(vars).length === 0)
                return false;

            const css = generateStylesheet(vars);
            const out = Gio.File.new_for_path(this._cssPath);
            out.get_parent()?.make_directory_with_parents(null);
            out.replace_contents(
                new TextEncoder().encode(css),
                null,
                false,
                Gio.FileCreateFlags.REPLACE_DESTINATION,
                null);

            const theme = St.ThemeContext.get_for_stage(global.stage).get_theme();
            theme.load_stylesheet(Gio.File.new_for_path(this._cssPath));
            return true;
        } catch (e) {
            logError(e, 'MatugenTheme.apply');
            return false;
        }
    }

    _startMonitor() {
        try {
            this._monitorId = this._file.monitor(
                Gio.FileMonitorFlags.NONE, null);
            this._monitorId.connect('changed',
                (_mon, _file, _other, event) => {
                    if (event === Gio.FileMonitorEvent.CHANGES_DONE_HINT ||
                        event === Gio.FileMonitorEvent.CHANGED) {
                        if (this._sourceId)
                            GLib.source_remove(this._sourceId);
                        this._sourceId = GLib.timeout_add_once(
                            GLib.PRIORITY_DEFAULT, 250, () => {
                                this._sourceId = 0;
                                this._load();
                            });
                    }
                });
        } catch (e) {
            logError(e, 'MatugenTheme._startMonitor');
        }
    }

    destroy() {
        try {
            if (this._monitorId) {
                this._monitorId.cancel();
                this._monitorId = null;
            }
        } catch {}
        try {
            const theme = St.ThemeContext.get_for_stage(global.stage)?.get_theme();
            theme?.unload_stylesheet?.(Gio.File.new_for_path(this._cssPath));
        } catch {}
    }
}